#! /bin/sh

bspc rule -r "*"
sxhkd &
compton -b -c &
nitrogen --restore &
unclutter &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d     
bspc monitor -d     

bspc config top_padding         24
bspc config border_width         2
bspc config window_gap          10

# Border colors
# bspc config normal_border_color "#484848"
# bspc config focused_border_color "#1F8999"
# bspc config urgent_border_color "#B58900"
# bspc config presel_border_color "#26E2FF"

##Color settings
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#99CC99"
bspc config normal_border_color "#000000"
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"
bspc config focused_private_border_color "#35BF5C"
bspc config border_width 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'follow=on
bspc rule -a SeaMonkey desktop='^2'follow=on
bspc rule -a SeaMonkey:Download state=floating
bspc rule -a SeaMonkey:Places state=floating
bspc rule -a MPlayer state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Mousepad state=floating
# bspc rule -a Pcmanfm state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

/home/house/.config/polybar/launch.sh &
